#!/bin/bash

# Install Grav on NGINX (Ubuntu and Debian)
# @Author Tyler Cosgrove

# Variables
APPNAME=grav
grav_branch=master
readonly grav_linux_distro=$(lsb_release -i | awk '{print $3}')


# Define echo function
# Purple color
function grav_prompt()
{
    echo $(tput setaf 5)$@$(tput sgr0)
}
# Blue color
function grav_echo()
{
    echo $(tput setaf 6)$@$(tput sgr0)
}
# White color
function grav_echo_info()
{
    echo $(tput setaf 7)$@$(tput sgr0)
}
# Green color
function grav_echo_success()
{
    echo $(tput setaf 2)$@$(tput sgr0)
}
# Red color
function grav_echo_fail()
{
    echo $(tput setaf 1)$@$(tput sgr0)
}
# Capture errors
function grav_echo_error()
{
    echo "[ `date` ] $(tput setaf 1)$@$(tput sgr0)"
    exit $2
}


function install_nginx
{
    grav_echo "Installing NGINX"
    apt-get install -y nginx &>> /dev/null || grav_echo_error "Unable to install NGINX"
    grav_echo_success "Finished Installing NGINX"
}

function install_php_nginx
{
    grav_echo "Installing PHP (NGINX)"
    apt-get install -y php5-fpm php5-cli php5-curl &>> /dev/null || grav_echo_error "Unable to install PHP"

    # Configure PHP Processor
    sed -i s/\;cgi\.fix_pathinfo\s*\=\s*1/cgi.fix_pathinfo\=0/ /etc/php5/fpm/php.ini
    service php5-fpm restart
    grav_echo_success "Finished Installing NGINX"
}

function configure_nginx
{
    grav_echo "Configuring NGINX"
    if [ -z "$1" ]; then
        grav_echo_error "ERROR: Not enough args passed to 'configure_nginx'. Exiting..."
    elif [ ! -e "$1" ]; then
        grav_echo_error "ERROR: File passed to 'configure_nginx' does not exist: $1 "
    fi
    sed -i "s|\/home\/USER\/www\/html;|\/home\/"${SUDO_USER:-$(whoami)}"\/www\/html;|g" $1 &>> /dev/null || grav_echo_erro "Issue setting server root"
    sed "s|server_name localhost;|"${2:-localhost}"|g" $1 &>> /dev/null || grav_echo_error "Issue replacing server name"
    cp $1 /etc/nginx/sites-available/$APPNAME
    if [ -e /etc/nginx/sites-enabled/$APPNAME ]; then
        rm /etc/nginx/sites-enabled/$APPNAME
    fi
    rm /etc/nginx/sites-enabled/default
    ln -s /etc/nginx/sites-available/$APPNAME /etc/nginx/sites-enabled/$APPNAME
    
    service nginx restart
    grav_echo_success "Finished Configuring NGINX"
}

function install_grav
{
    grav_echo "Installing Grav..."
    git clone -b $grav_branch https://github.com/getgrav/grav.git /tmp/grav --quiet|| grav_echo_error "Unable to clone Grav, exit status" $?
    root=/home/${SUDO_USER:-$(whoami)}/www/html
    rm -Rf $root
    if [ ! -d $root ]; then
        mkdir -p /home/${SUDO_USER:-$(whoami)}/www
    fi
    mv /tmp/grav $root
    rm -Rf /tmp/grav
    cd $root
    chown ${SUDO_USER:-$(whoami)}:www-data .
    chown -R ${SUDO_USER:-$(whoami)}:www-data *
    find . -type f | xargs chmod 664
    find ./bin -type f | xargs chmod 775
    find . -type d | xargs chmod 775
    find . -type d | xargs chmod +s
    su - $SUDO_USER -c "cd "$root"&&umask 0002&&bin/grav install&&bin/grav clear"
    configure_nginx /home/${SUDO_USER:-$(whoami)}/www/html/webserver-configs/nginx.conf
    grav_echo ""
    
    grav_echo_success "Finished Installing Grav"
}

function initialize
{
    grav_echo "Initializing..."
    apt-get update &>> /dev/null || grav_echo_fail "Unable to update system"
    # apt-get -y upgrade &>> /dev/null || grav_echo_fail "Unable to upgrade system"
    # Checking lsb_release package
    if [ ! -x /usr/bin/lsb_release ]; then
        grav_echo "Installing lsb-release, please wait..."
        apt-get -y install lsb-release &>> /dev/null
    fi

    # Checking linux distro
    if [ "$grav_linux_distro" != "Ubuntu" ] && [ "$grav_linux_distro" != "Debian" ]; then
        grav_echo_fail "This installer is made for Ubuntu and Debian only as of now"
        grav_echo_fail "This installer only supports Ubuntu 12.04/14.04 and Debian 7.x/8.x"
        exit 100
    fi

    # Installer only supports all Ubuntu/Debian distro except the distro reached EOL
    lsb_release -d | egrep -e "12.04|14.04|wheezy|jessie" &>> /dev/null
    if [ "$?" -ne "0" ]; then
        grav_echo_fail "This installer only supports Ubuntu 12.04/14.04 and Debian 7.x/8.x"
        exit 100
    fi
}

# Checking permissions
if [[ $EUID -ne 0 ]]; then
    grav_echo_fail "Sudo privilege required..."
    exit 100
fi

initialize
install_nginx
install_php_nginx
install_grav
